Update websocketpp to e036a5au to fix compilation
Under Arch Linux (and Ubuntu 17.10 according to #196), compilation fails
with an error in websocketpp: "error: no matching function for call to
‘make_shared(std::reference_wrapper<boost::asio::io_context>)’".

To resolve this, update websocketpp to e036a5au which is the first
revision after ac5d7ea5 which compiles without warnings being generated.

Fixes #196.